{{/* default values */}}
{{- define "backup.velero.defaultValues" }}
# volumes are backed up via Restic node agent
# CSI Snapshots is not suffisent if they are not persisted somewhere else
snapshotsEnabled: false
deployNodeAgent: true
kubectl:
  image:
    # debian version must be the same as velero Dockerfile for binary compatiblily: https://github.com/vmware-tanzu/velero/blob/main/Dockerfile
    repository: jfcoz/kubectl-deb12-basic
    # sera inutile apres le merge/release de https://github.com/vmware-tanzu/helm-charts/pull/706
nodeAgent:
  tolerations:
    - effect: NoSchedule
      key: master
      operator: Exists
    - effect: NoSchedule
      key: storage
      operator: Exists
  resources:
    requests:
      cpu: 5m
      memory: 100Mi
    limits:
      memory: 500Mi
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 50%
resources:
  requests:
    cpu: 0m
    memory: 300Mi
  limits:
    cpu: 1
    # trivy sbom export is memory intensive
    memory: 1500Mi
## done by fluxcd
#upgradeCRDs: false
## when CRD ard installed before via fluxcd/argocd
#helmHookAnnotations: false
# until https://github.com/vmware-tanzu/helm-charts/issues/515
upgradeJobResources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi
configuration:
  defaultVolumesToFsBackup: true
  logLevel: info
  backupStorageLocation:
    - name: default
      provider: velero.io/aws
      bucket: velero-k3s
      config:
        # TODO
        s3Url: "https://s3.sbg.io.cloud.ovh.net"
        s3ForcePathStyle: "true"
        region: "sbg"
        # https://github.com/vmware-tanzu/velero/issues/7952#issuecomment-2197234521
        checksumAlgorithm: ""
credentials:
  existingSecret: cloud-credentials
initContainers:
  - name: velero-plugin-for-aws
    # compatibility : https://github.com/vmware-tanzu/velero-plugin-for-aws/#compatibility
    image: velero/velero-plugin-for-aws:v1.13.2
    volumeMounts:
      - name: plugins
        mountPath: /target
schedules:
  nightly:
    schedule: "29 3 * * *"
    template:
      # One month
      ttl: "744h"
      excludedResources:
      # *sbomreports can lead to velero out of memory and will be regenerated by trivy
      - clustersbomreports.aquasecurity.github.io
      - sbomreports.aquasecurity.github.io
metrics:
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
    spec:
      - alert: VeleroPartialFailure
        expr: sum(rate(velero_backup_partial_failure_total{schedule=~".+"}[1d])) by (schedule) > 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: 'At least one Velero partial backup failure on schedule {{ "{{" }} $labels.schedule }}'
      - alert: VeleroBackupFailure
        expr: sum(rate(velero_backup_failure_total{schedule=~".+"}[1d])) by (schedule) > 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: 'At least one Velero backup failure on schedule {{ "{{" }} $labels.schedule }}'
      - alert: VeleroVolumeSnapshotFailure
        expr: sum(rate(velero_volume_snapshot_failure_total{schedule=~".+"}[1d])) by (schedule) > 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: 'At least one Velero volume snapshot failure on schedule {{ "{{" }} $labels.schedule }}'
      - alert: VeleroBackupDeletionFailure
        expr: sum(rate(velero_backup_deletion_failure_total{schedule=~".+"}[1d])) by (schedule) > 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: 'At least one Velero backup deletion failure on schedule {{ "{{" }} $labels.schedule }}'
      - alert: VeleroMissingSchedule
        expr: sum(rate(velero_backup_attempt_total{schedule=~".+"}[1d])) by (schedule) == 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: 'No Velero backup since one day on schedule {{ "{{" }} $labels.schedule }}'
{{- end }}

{{/* merged values : default + user  */}}
{{- define "backup.velero.mergedValues" }}
{{- $me := .Values.components.backup.velero }}
{{- $defaultValues := include "backup.velero.defaultValues" . | fromYaml }}
{{- $customValues := $me.values | default dict }}
{{- mergeOverwrite $defaultValues $customValues | toYaml }}
{{- end }}
