{{/* default values */}}
{{- define "backup.velero.defaultValues" }}
{{- $me := .Values.components.backup.velero }}
# volumes are backed up via Restic node agent
# CSI Snapshots is not suffisent if they are not persisted somewhere else

{{- if or
  (eq .Values.cloudProvider "none")
}}
# do not rely on storage snaspshots
snapshotsEnabled: false
{{- end }}

{{- if or
  (eq .Values.cloudProvider "none")
  (eq .Values.cloudProvider "scw")
}}
# enable NodeAgent to allow File System Backup when storageClass does not support snapshot (Scaleway Filestore, Cephfs...)
deployNodeAgent: true
{{- end }}


nodeAgent:
  tolerations:
    - effect: NoSchedule
      operator: Exists
  resources:
    requests:
      cpu: 5m
      memory: 100Mi
    limits:
      memory: 500Mi
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 50%

kubectl:
  image:
    # debian version must be the same as velero Dockerfile for binary compatiblily: https://github.com/vmware-tanzu/velero/blob/main/Dockerfile
    repository: jfcoz/kubectl-deb12-basic
    # sera inutile apres le merge/release de https://github.com/vmware-tanzu/helm-charts/pull/706


revisionHistoryLimit: 3
resources:
  requests:
    cpu: 0m
    memory: 300Mi
  limits:
    cpu: 1
    # trivy sbom export is memory intensive
    memory: 1500Mi

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict-local-volumes: plugins,scratch
## done by fluxcd
#upgradeCRDs: false
## when CRD ard installed before via fluxcd/argocd
#helmHookAnnotations: false

# until https://github.com/vmware-tanzu/helm-charts/issues/515
upgradeJobResources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

configuration:
  {{- if or
    (eq .Values.cloudProvider "none")
  }}
  defaultVolumesToFsBackup: true
  {{- end }}

  logLevel: info
  backupStorageLocation:
    {{- include "backup.velero.backupStorageLocation" . | nindent 4 }}

  {{- if or
    (eq .Values.cloudProvider "scw")
  }}
  # we use CSI snapshot on Scaleway because scaleway plugin does not exists
  # volumeSnapshotClass scw-snapshot needs to have the annotation:
  # snapshot.storage.kubernetes.io/is-default-class: "true"
  features: EnableCSI

  # remove default empty volumeSnapshotLocation
  volumeSnapshotLocation: []
  {{- end }}

credentials:
  existingSecret: cloud-credentials

{{- if $me.config.encryption.enabled }}
extraVolumeMounts:
- name: encryption-key
  mountPath: /encryption

extraVolumes:
- name: encryption-key
  secret:
    secretName: {{ $me.config.encryption.secretName }}
{{- end }}

initContainers:
  - name: velero-plugin-for-aws
    # compatibility : https://github.com/vmware-tanzu/velero-plugin-for-aws/#compatibility
    image: velero/velero-plugin-for-aws:v1.13.2
    volumeMounts:
      - name: plugins
        mountPath: /target

schedules:
  nightly:
    schedule: "29 3 * * *"
    template:
      # One month
      ttl: "744h"
      excludedResources:
      # *sbomreports can lead to velero out of memory and will be regenerated by trivy
      - clustersbomreports.aquasecurity.github.io
      - sbomreports.aquasecurity.github.io
      {{- if or
        (eq .Values.cloudProvider "scw")
      }}
      resourcePolicy:
        kind: ConfigMap
        name: velero-resource-policies
      {{- end }}


{{- if or
  (eq .Values.cloudProvider "scw")
}}
configMaps:
  resource-policies:
    data:
      policies.yaml: |
        version: v1
        volumePolicies:
          - conditions:
              csi:
                {{- if (eq .Values.cloudProvider "scw") }}
                driver: filestorage.csi.scaleway.com
                {{- end }}
            action:
              type: fs-backup
{{- end }}


metrics:
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
    spec:
      - alert: VeleroPartialFailure
        expr: sum(rate(velero_backup_partial_failure_total{schedule=~".+"}[1d])) by (schedule) > 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: 'At least one Velero partial backup failure on schedule {{ "{{" }} $labels.schedule }}'
      - alert: VeleroBackupFailure
        expr: sum(rate(velero_backup_failure_total{schedule=~".+"}[1d])) by (schedule) > 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: 'At least one Velero backup failure on schedule {{ "{{" }} $labels.schedule }}'
      - alert: VeleroVolumeSnapshotFailure
        expr: sum(rate(velero_volume_snapshot_failure_total{schedule=~".+"}[1d])) by (schedule) > 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: 'At least one Velero volume snapshot failure on schedule {{ "{{" }} $labels.schedule }}'
      - alert: VeleroBackupDeletionFailure
        expr: sum(rate(velero_backup_deletion_failure_total{schedule=~".+"}[1d])) by (schedule) > 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: 'At least one Velero backup deletion failure on schedule {{ "{{" }} $labels.schedule }}'
      - alert: VeleroMissingSchedule
        expr: sum(rate(velero_backup_attempt_total{schedule=~".+"}[1d])) by (schedule) == 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: 'No Velero backup since one day on schedule {{ "{{" }} $labels.schedule }}'
{{- end }}

{{/* merged values : default + user  */}}
{{- define "backup.velero.mergedValues" }}
{{- $me := .Values.components.backup.velero }}
{{- $defaultValues := include "backup.velero.defaultValues" . | fromYaml }}
{{- $customValues := $me.values | default dict }}
{{- mergeOverwrite $defaultValues $customValues | toYaml }}
{{- end }}
