# cloudProvider aws/gcp/ovh/scw (Scaleway)/do (Digital Ocean)/none
cloudProvider: none
multiZone: true

# kind/k3s
kubernetesDistribution: none

general:
  clusterName: change-me
  # contactAddress: replaced.by.kustomization
  # grafanaAdminPassword: must.be.replaced.by.kustomization
  # clusterName: must.be.replaced.by.kustomization

  # each ingress/loadbalancer entrypoint should have a *.cluster.example.com DNS record
  # dnsWildcardSuffixes:
  #   ingress:
  #     nginx: replaced.by.kustomization
  #   gateway:
  #     cilium: replaced.by.kustomization

  kubernetesApi:
    # host: replaced.by.kustomization
    port: 6443

  # on cloud providers with small ETCD quotas, it help to reduce database size by keeping less history of each application
  revisionHistoryLimit: 3

  fluxcd:
    release:
      interval: 1h
      timeout: 10m
      maxHistory: 3
      install:
        crds: Create
        remediation:
          retries: 10
      upgrade:
        crds: CreateReplace
        remediation:
          retries: 3
      test:
        enable: true

features:
  gatewayAPI:
    enabled: true
    type: experimental

repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: cilium
    url: https://helm.cilium.io/
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: datadog
    url: https://helm.datadoghq.com
  - name: enix
    url: oci://quay.io/enix/charts
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: falcosecurity
    url: https://falcosecurity.github.io/charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: grafana-community
    url: https://grafana-community.github.io/helm-charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: kedacore
    url: https://kedacore.github.io/charts
  - name: kubernetes-ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: kyverno
    url: https://kyverno.github.io/kyverno/
  - name: opentelemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: scaleway
    url: https://helm.scw.cloud/
  - name: stevehipwell
    url: https://stevehipwell.github.io/helm-charts/
  - name: vmware-tanzu
    url: https://vmware-tanzu.github.io/helm-charts

components:

  cni:
    cilium:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: kube-system
      chart:
        name: cilium
        version: "1.19.6"
        repository: cilium
      release:
        timeout: 30m
      values: {}

    # On Scaleway, Hubble must be deployed as an addon: https://www.scaleway.com/en/docs/tutorials/deploying-hubble-add-on-scaleway-kubernetes-clusters/
    ciliumScwHubble:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      chart:
        name: scaleway-cilium-hubble
        version: "0.1.4"
        repository: scaleway

  gitops:
    argocd:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-argocd
      chart:
        name: argo-cd
        version: "10.6.3"
        repository: argo
      issuer: letsencrypt-production
      release:
        timeout: 5m
      dex_connectors: {}
        # github:
        #   client:
        #     # create oauth app from:
        #     # organization app: https://github.com/organizations/$org_name/settings/applications
        #     # personal app: https://github.com/settings/applications/new
        #     # recommended setup:
        #     #   application name: ${cluster_name}-argocd
        #     #   homepage url: https://argocd.{ingressWildcardSuffix}/
        #     #   application description: ArgoCD on ${cluster_name} cluster
        #     #   authorization callback url: https://argocd.{ingressWildcardSuffix}/api/dex/callback
        #     id: my_github_client_id
        #     secret: my_github_client_secret
        #   orgs:
        #     - name: orgname
        #       teams:
        #       - team1
        #       - team2
      values: {}
        # configs:
        #   rbac:
        #     policy.csv: |
        #       g, coopTilleuls:lt-sre, role:admin
        #     policy.default: role:readonly
        # dex:
        #   logLevel: debug
        # server:
        #   httproute:
        #     parentRefs:
        #     - group: gateway.networking.k8s.io
        #       kind: Gateway
        #       name: scaleway-gateway-par1
        #       namespace: kube-system
        #       sectionName: https-prometheus
        #     - group: gateway.networking.k8s.io
        #       kind: Gateway
        #       name: scaleway-gateway-par2
        #       namespace: kube-system
        #       sectionName: https-prometheus


    argocdImageUpdater:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-argocd
      chart:
        name: argocd-image-updater
        version: "1.2.4"
        repository: argo
      values: {}

    fluxcd:
      namespace: flux-system

  ingress:
    nginxIngressController:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-nginx-ingress
      chart:
        name: ingress-nginx
        version: "4.15.1"
        repository: kubernetes-ingress-nginx
      release:
        timeout: 30m
      values: {}

  monitoring:
    datadog:
      namespace: infra-datadog
      managed: false
      used: false
      helmResourcePolicyKeep: true
      chart:
        name: datadog
        version: "3.241.0"
        repository: datadog
      release:
        timeout: 5m
      config: {}
        # https://app.datadoghq.eu/organization-settings/api-keys
        # apiKey: change_me
      values: {}

    keda:
      namespace: infra-keda
      managed: false
      used: false
      helmResourcePolicyKeep: true
      chart:
        name: keda
        version: "2.20.2"
        repository: kedacore
      release:
        timeout: 5m
      values: {}

    kubePrometheusStack:
      namespace: infra-prometheus
      managed: false
      used: false
      helmResourcePolicyKeep: true
      chart:
        name: kube-prometheus-stack
        version: "88.6.3"
        repository: prometheus-community
      excludeFromBackup: true
      release:
        timeout: 10m
      config:
        alerts: {}
          # watchdog: https://replace_with_webhook.example.com
          # critical_wakeup_oncall: https://replace_with_webhook.example.com
          # critical_tomorrow_oncall: https://replace_with_webhook.example.com
          # warning_oncall: https://replace_with_webhook.example.com
          # info_slack: https://replace_with_webhook.example.com
          # falco_slack: https://replace_with_webhook.example.com
        customRoutes:
          severityCritical: []
          # - matchers:
          #     - label_servicelevel="7h_5d"
          #   routes:
          #     - receiver: critical_tomorrow_oncall
          # - matchers:
          #     - label_servicelevel="24h_7d"
          #   routes:
          #     - receiver: critical_wakeup_oncall
          # - matchers:
          #     - label_servicelevel="0h_0d"
          #   routes:
          #     - receiver: info_slack
          severityCriticalTomorrow: []
          # - matchers:
          #     - label_servicelevel="7h_5d"
          #   routes:
          #     - receiver: critical_tomorrow_oncall
          # - matchers:
          #     - label_servicelevel="24h_7d"
          #   routes:
          #     - receiver: critical_tomorrow_oncall
          # - matchers:
          #     - label_servicelevel="0h_0d"
          #   routes:
          #     - receiver: info_slack
          severityWarning: []
          # - matchers:
          #     - label_servicelevel="7h_5d"
          #   routes:
          #     - receiver: info_slack
          # - matchers:
          #     - label_servicelevel="24h_7d"
          #   routes:
          #     - receiver: info_slack
          # - matchers:
          #     - label_servicelevel="0h_0d"
          #   routes:
          #     - receiver: "null"
      values: {}
        # alertmanager:
        #   config:
        #     # setting anything here overwrite all default helm-chart-of-the-death configuration
        # grafana:
        #   route:
        #     main:
        #       parentRefs:
        #       - group: gateway.networking.k8s.io
        #         kind: Gateway
        #         name: scaleway-gateway-par1
        #         namespace: kube-system
        #         sectionName: https-prometheus
        #       - group: gateway.networking.k8s.io
        #         kind: Gateway
        #         name: scaleway-gateway-par2
        #         namespace: kube-system
        #         sectionName: https-prometheus
        #     redirect:
        #       parentRefs:
        #       - group: gateway.networking.k8s.io
        #         kind: Gateway
        #         name: scaleway-gateway-par1
        #         namespace: kube-system
        #         sectionName: http
        #       - group: gateway.networking.k8s.io
        #         kind: Gateway
        #         name: scaleway-gateway-par2
        #         namespace: kube-system
        #         sectionName: http


    thanos:
      namespace: infra-thanos
      managed: false
      used: false
      helmResourcePolicyKeep: true
      chart:
        name: thanos
        version: "1.23.1"
        repository: stevehipwell
      excludeFromBackup: true
      release:
        timeout: 5m
      values: {}

    loki:
      namespace: infra-loki
      managed: false
      used: false
      helmResourcePolicyKeep: true
      chart:
        name: loki
        version: "7.3.0"
        repository: grafana
      excludeFromBackup: true
      release:
        timeout: 20m
      config:
        # deploymentMode: SimpleScalable / Distributed / SingleBinary
        deploymentMode: SimpleScalable
        # buckets:
        #   chunks: "change_me"
        # aws:
        #   roleArn: "change_me"
        #   region: "change_me"
      values: {}

    promtail:
      namespace: infra-promtail
      managed: false
      used: false
      helmResourcePolicyKeep: true
      chart:
        name: promtail
        version: "6.17.1"
        repository: grafana
      release:
        timeout: 30m
      values: {}

    k8sMonitoring:
      namespace: infra-k8s-monitoring
      managed: false
      used: false
      helmResourcePolicyKeep: true
      chart:
        name: k8s-monitoring
        version: "4.5.0"
        repository: grafana
      release:
        timeout: 5m
      values: {}


    openTelemetryOperator:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-opentelemetry
      chart:
        name: opentelemetry-operator
        version: "0.122.0"
        repository: opentelemetry
      release:
        timeout: 5m
        install:
          # temporaire pour featureGates string et map en cours de switch
          disableSchemaValidation: true
        upgrade:
          # temporaire pour featureGates string et map en cours de switch
          disableSchemaValidation: true
      values: {}

    openTelemetryCollector:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-opentelemetry
      values: {}

    x509CertificateExporter:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-x509
      chart:
        name: x509-certificate-exporter
        version: "4.1.0"
        repository: enix
      release:
        timeout: 10m
      values: {}

    pushGateway:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-push-gateway
      chart:
        name: prometheus-pushgateway
        version: "3.8.0"
        repository: prometheus-community
      release:
        timeout: 5m
      values: {}

    tempo:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-tempo
      chart:
        name: tempo-distributed
        version: "2.26.2"
        repository: grafana-community
      excludeFromBackup: true
      release:
        timeout: 10m
      values: {}

    smartctlExporter:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-smartctl-exporter
      chart:
        name: prometheus-smartctl-exporter
        version: "0.17"
        repository: prometheus-community
      release:
        timeout: 10m
      values: {}

    eventRouter:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-event-router
      values: {}

    blackboxExporter:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-blackbox-exporter
      chart:
        name: prometheus-blackbox-exporter
        version: "11.18.0"
        repository: prometheus-community
      release:
        timeout: 5m
      values: {}

    postgresqlExporter:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-prometheus
      chart:
        name: prometheus-postgres-exporter
        version: "8.2.0"
        repository: prometheus-community
      release:
        timeout: 5m
      values: {}


  backup:
    velero:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-velero
      chart:
        name: velero
        version: "12.1.0"
        repository: vmware-tanzu
      release:
        timeout: 10m
      config:
        # bucket: "change_me"
        # aws:
        #   roleArn: "change_me"
        #   region: "change_me"
        encryption:
          enabled: false
          secretName: velero-repo-encryption
          keyName: encryption.key
      values: {}

  security:
    certManager:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-cert-manager
      chart:
        name: cert-manager
        version: "v1.21.1"
        repository: jetstack
      release:
        timeout: 5m
      issuers:
        letsencrypt: true
        selfsigned: false
      values: {}

    externalSecrets:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-external-secrets
      chart:
        name: external-secrets
        version: "2.10.0"
        repository: external-secrets
      release:
        timeout: 5m
      values: {}


    kyverno:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-kyverno
      chart:
        name: kyverno
        version: "3.8.2"
        repository: kyverno
      release:
        timeout: 10m
      values: {}

    falco:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-falco
      chart:
        name: falco
        version: "9.1.0"
        repository: falcosecurity
      excludeFromBackup: true
      release:
        timeout: 10m
        test:
          # test is using a very old mono arch image
          # https://github.com/falcosecurity/charts/blob/master/charts/falcosidekick/templates/tests/test-connection.yaml#L16
          enable: false
      config:
        alerts:
          # where to route falco alerts by priority
          emergency: critical_wakeup_oncall
          critical: critical_tomorrow_oncall
          others: falco_slack
      values: {}

    trivy:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-trivy
      chart:
        name: TODO
        version: "TODO"
        repository: TODO
      release:
        timeout: 10m
      values: {}

  audit:
    popeye:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-popeye

  storage:
    rook:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: rook-ceph
      chart:
        version: "TODO"
        repository: TODO
      values: {}

  database:
    cnpg:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: cnpg-operator
      chart:
        name: cloudnative-pg
        version: "0.29.0"
        repository: cnpg
      release:
        timeout: 5m
      values: {}

    cnpgPluginBarmanCloud:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      chart:
        name: plugin-barman-cloud
        version: "0.7.1"
        repository: cnpg
      release:
        timeout: 5m
      values: {}


cloudProviderSpecific:
  aws:
    cloudwatchAgent:
      used: false
    fluentd:
      used: false
