# cloudProvider aws/gcp/ovh/scw/do/none
cloudProvider: none
multiZone: true

# kind/k3s
kubernetesDistribution: none

general:
  # clusterName: change-me
  # ingressWildcardSuffix: replaced.by.kustomization
  # contactAddress: replaced.by.kustomization
  # grafanaAdminPassword: must.be.replaced.by.kustomization
  # clusterName: must.be.replaced.by.kustomization

  kubernetesApi:
    host: replaced.by.kustomization
    port: 6443

  fluxcd:
    release:
      interval: 1h
      timeout: 10m
      install:
        crds: Create
        remediation:
          retries: 10
      upgrade:
        crds: CreateReplace
        remediation:
          retries: 3
      test:
        enable: true


repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: cilium
    url: https://helm.cilium.io/
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: datadog
    url: https://helm.datadoghq.com
  - name: enix
    url: https://charts.enix.io
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: falcosecurity
    url: https://falcosecurity.github.io/charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: grafana-community
    url: https://grafana-community.github.io/helm-charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: kedacore
    url: https://kedacore.github.io/charts
  - name: kubernetes-ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: kyverno
    url: https://kyverno.github.io/kyverno/
  - name: opentelemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: stevehipwell
    url: https://stevehipwell.github.io/helm-charts/
  - name: vmware-tanzu
    url: https://vmware-tanzu.github.io/helm-charts

components:

  cni:
    cilium:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: kube-system
      chart:
        name: cilium
        version: "1.19.2"
        repository: cilium
      release:
        timeout: 30m
      values: {}

  gitops:
    argocd:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-argocd
      chart:
        name: argo-cd
        version: "9.4.17"
        repository: argo
      issuer: letsencrypt-production
      release:
        timeout: 5m
      dex_connectors: {}
      #  github:
      #    client:
      #      # create oauth app from https://github.com/settings/applications/new
      #      id: my_github_client_id
      #      secret: my_github_client_secret
      #    orgs:
      #      - name: orgname
      #        teams:
      #        - team1
      #        - team2
      values: {}

    argocdImageUpdater:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: infra-argocd
      chart:
        name: argocd-image-updater
        version: "1.1.4"
        repository: argo
      values: {}

    fluxcd:
      namespace: flux-system

  ingress:
    nginxIngressController:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-nginx-ingress
      chart:
        name: ingress-nginx
        version: "4.15.1"
        repository: kubernetes-ingress-nginx
      release:
        timeout: 30m
      values: {}

  monitoring:
    datadog:
      namespace: infra-datadog
      managed: false
      used: true
      helmResourcePolicyKeep: true
      chart:
        name: datadog
        version: "3.193.0"
        repository: datadog
      release:
        timeout: 5m
      values: {}

    keda:
      namespace: infra-keda
      managed: false
      helmResourcePolicyKeep: true
      chart:
        name: keda
        version: "2.19.0"
        repository: kedacore
      release:
        timeout: 5m
      values: {}

    kubePrometheusStack:
      namespace: infra-prometheus
      managed: false
      helmResourcePolicyKeep: true
      chart:
        name: kube-prometheus-stack
        version: "82.13.6"
        repository: prometheus-community
      excludeFromBackup: true
      release:
        timeout: 10m
      values: {}

    thanos:
      namespace: infra-thanos
      managed: false
      helmResourcePolicyKeep: true
      chart:
        name: thanos
        version: "1.23.0"
        repository: stevehipwell
      excludeFromBackup: true
      release:
        timeout: 5m
      values: {}

    loki:
      namespace: infra-loki
      managed: false
      helmResourcePolicyKeep: true
      chart:
        name: loki
        version: "6.55.0"
        repository: grafana
      excludeFromBackup: true
      release:
        timeout: 20m
      config:
        # deploymentMode: SimpleScalable / Distributed / SingleBinary
        deploymentMode: SimpleScalable
        # buckets:
        #   chunks: "change_me"
        # aws:
        #   roleArn: "change_me"
        #   region: "change_me"
      values: {}

    promtail:
      namespace: infra-promtail
      managed: false
      helmResourcePolicyKeep: true
      chart:
        name: promtail
        version: "6.17.1"
        repository: grafana
      release:
        timeout: 30m
      values: {}

    k8sMonitoring:
      namespace: infra-k8s-monitoring
      managed: false
      helmResourcePolicyKeep: true
      chart:
        name: k8s-monitoring
        version: "3.8.4"
        repository: grafana
      release:
        timeout: 5m
      values: {}


    openTelemetryOperator:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-opentelemetry
      chart:
        name: opentelemetry-operator
        version: "0.108.0"
        repository: opentelemetry
      release:
        timeout: 5m
        install:
          # temporaire pour featureGates string et map en cours de switch
          disableSchemaValidation: true
        upgrade:
          # temporaire pour featureGates string et map en cours de switch
          disableSchemaValidation: true
      values: {}

    openTelemetryCollector:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-opentelemetry
      values: {}

    x509CertificateExporter:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-x509
      chart:
        name: x509-certificate-exporter
        version: "3.19.1"
        repository: enix
      release:
        timeout: 10m
      values: {}

    pushGateway:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-push-gateway
      chart:
        name: prometheus-pushgateway
        version: "3.6.0"
        repository: prometheus-community
      release:
        timeout: 5m
      values: {}

    tempo:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-tempo
      chart:
        name: tempo-distributed
        version: "2.6.5"
        repository: grafana-community
      excludeFromBackup: true
      release:
        timeout: 10m
      values: {}

    smartctlExporter:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-smartctl-exporter
      chart:
        name: prometheus-smartctl-exporter
        version: "0.16"
        repository: prometheus-community
      release:
        timeout: 10m
      values: {}

    eventRouter:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-event-router
      values: {}

    blackboxExporter:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-blackbox-exporter
      chart:
        name: prometheus-blackbox-exporter
        version: "11.9.1"
        repository: prometheus-community
      release:
        timeout: 5m
      values: {}

  backup:
    velero:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-velero
      chart:
        name: velero
        version: "12.0.0"
        repository: vmware-tanzu
      release:
        timeout: 10m
      config:
        # bucket: "change_me"
        # aws:
        #   roleArn: "change_me"
        #   region: "change_me"
        encryption:
          enabled: false
          secretName: velero-repo-encryption
          keyName: encryption.key
  values: {}

  security:
    certManager:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-cert-manager
      chart:
        name: cert-manager
        version: "v1.20.1"
        repository: jetstack
      release:
        timeout: 5m
      issuers:
        letsencrypt: true
        selfsigned: false
      values: {}

    externalSecrets:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-external-secrets
      chart:
        name: external-secrets
        version: "2.2.0"
        repository: external-secrets
      release:
        timeout: 5m
      values: {}


    kyverno:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-kyverno
      chart:
        name: kyverno
        version: "3.6.2"
        repository: kyverno
      release:
        timeout: 10m
      values: {}

    falco:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-falco
      chart:
        name: falco
        version: "8.0.1"
        repository: falcosecurity
      excludeFromBackup: true
      release:
        timeout: 10m
        test:
          # test is using a very old mono arch image
          # https://github.com/falcosecurity/charts/blob/master/charts/falcosidekick/templates/tests/test-connection.yaml#L16
          enable: false
      values: {}

    trivy:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-trivy
      chart:
        name: TODO
        version: "TODO"
        repository: TODO
      release:
        timeout: 10m
      values: {}

  audit:
    popeye:
      managed: false
      helmResourcePolicyKeep: true
      namespace: infra-popeye

  storage:
    rook:
      managed: false
      used: false
      helmResourcePolicyKeep: true
      namespace: rook-ceph
      chart:
        version: "TODO"
        repository: TODO
      values: {}

  database:
    cnpg:
      managed: false
      helmResourcePolicyKeep: true
      namespace: cnpg-operator
      chart:
        name: cloudnative-pg
        version: "0.27.1"
        repository: cnpg
      release:
        timeout: 5m
      values: {}

    cnpgPluginBarmanCloud:
      managed: false
      helmResourcePolicyKeep: true
      chart:
        name: plugin-barman-cloud
        version: "0.5.0"
        repository: cnpg
      release:
        timeout: 5m
      values: {}


cloudProviderSpecific:
  aws:
    cloudwatchAgent:
      used: false
    fluentd:
      used: false
