{{- $me := .Values.components.security.kyverno }}
{{- if include "common.managed" $me }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: {{ $me.namespace }}
  annotations:
    {{- if $me.helmResourcePolicyKeep }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  dependsOn:
    - name: kyverno
      namespace: {{ $me.namespace }}
  # include common.fluxcd.release
  {{- include "common.fluxcd.release" (list $ $me) | nindent 2 }}
  chart:
    spec:
      chart: kyverno-policies
      # each major contains upgrade process in changelog
      version: {{ $me.chart.version | quote }}
      sourceRef:
        kind: HelmRepository
        name: {{ $me.chart.repository | quote }}
        namespace: {{ $.Release.Namespace }}
      interval: 1h
  values:
    {{- include "security.kyverno.policies.mergedValues" . | nindent 4 }}
{{- end }}
