{{- $me := .Values.components.security.kyverno }}
{{- if (semverCompare ">=3.7.0" $me.chart.version) }}


{{- if include "common.used" .Values.components.cni.cilium }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: exclude-cilium-agent
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-capabilities
      kind: ValidatingPolicy
    - name: disallow-host-namespaces
      kind: ValidatingPolicy
    - name: disallow-host-path
      kind: ValidatingPolicy
    - name: disallow-host-ports
      kind: ValidatingPolicy
    - name: disallow-privileged-containers
      kind: ValidatingPolicy
    - name: disallow-selinux
      kind: ValidatingPolicy
    - name: restrict-seccomp
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace-and-app
      expression: "object.metadata.name.startsWith('cilium') && object.metadata.namespace == '{{ .Values.components.cni.cilium.namespace }}' && object.metatada.labels['app.kubernetes.io/name']=='cilium-agent'"
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: exclude-cilium-envoy
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-capabilities
      kind: ValidatingPolicy
    - name: disallow-host-namespaces
      kind: ValidatingPolicy
    - name: disallow-host-path
      kind: ValidatingPolicy
    - name: disallow-host-ports
      kind: ValidatingPolicy
    - name: disallow-selinux
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace-and-app
      expression: "object.metadata.name.startsWith('cilium-envoy') && object.metadata.namespace == '{{ .Values.components.cni.cilium.namespace }}' && object.metatada.labels['app.kubernetes.io/name']=='cilium-envoy'"
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: exclude-cilium-operator
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-namespaces
      kind: ValidatingPolicy
    - name: disallow-host-ports
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('cilium-operator') && object.metadata.namespace == '{{ .Values.components.cni.cilium.namespace }}'"
{{- end }}
---



{{- if include "common.used" .Values.components.storage.rook }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: rook-ceph-objectstore
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('rook-ceph-objectstore') && object.metadata.namespace == '{{ .Values.components.storage.rook.namespace }}'"
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: rook-ceph-osd
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-privileged-containers
      kind: ValidatingPolicy
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('rook-ceph-osd') && object.metadata.namespace == '{{ .Values.components.storage.rook.namespace }}'"
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: rook-ceph-exporter
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('rook-ceph-exporter') && object.metadata.namespace == '{{ .Values.components.storage.rook.namespace }}'"
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: rook-ceph-mds
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('rook-ceph-mds') && object.metadata.namespace == '{{ .Values.components.storage.rook.namespace }}'"
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: rook-ceph-mgr
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('rook-ceph-mgr') && object.metadata.namespace == '{{ .Values.components.storage.rook.namespace }}'"
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: rook-ceph-mon
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('rook-ceph-mon') && object.metadata.namespace == '{{ .Values.components.storage.rook.namespace }}'"
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: rook-ceph-csi-nodeplugin-cephfs
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-capabilities
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('rook-ceph.cephfs.csi.ceph.com-nodeplugin') && object.metadata.namespace == '{{ .Values.components.storage.rook.namespace }}'"
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: rook-ceph-csi-nodeplugin-rbd
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-capabilities
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('rook-ceph.rbd.csi.ceph.com-nodeplugin') && object.metadata.namespace == '{{ .Values.components.storage.rook.namespace }}'"
{{- end }}



---
{{- if include "common.used" .Values.components.monitoring.datadog }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: datadog-agent
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    {{- if and
           (include "common.used" .Values.components.monitoring.datadog)
           ( or
               (eq ((.Values.components.monitoring.datadog.values).discovery).enabled nil)
               ((.Values.components.monitoring.datadog.values).discovery).enabled
           )
    }}
    {{- /* if not set, discovery is enabled by default */}}
    - name: disallow-capabilities
      kind: ValidatingPolicy
    {{- end }}
    - name: disallow-host-namespaces
      kind: ValidatingPolicy
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace-and-component
      expression: "object.metadata.name.startsWith('datadog') && object.metadata.namespace == '{{ .Values.components.monitoring.datadog.namespace }}' && object.metatada.labels['app.kubernetes.io/component']=='agent'"
{{- end }}
---




{{- if include "common.used" .Values.components.monitoring.k8sMonitoring }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: k8s-monitoring-allow-logs
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-capabilities
      kind: ValidatingPolicy
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('k8s-monitoring-alloy-logs') && object.metadata.namespace == '{{ .Values.components.monitoring.k8sMonitoring.namespace }}'"
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: k8s-monitoring-allow-singleton
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-capabilities
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('k8s-monitoring-alloy-singleton') && object.metadata.namespace == '{{ .Values.components.monitoring.k8sMonitoring.namespace }}'"
{{- end }}
---




{{- if eq .Values.cloudProvider "scw" }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: scaleway-csi
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-capabilities
      kind: ValidatingPolicy
    - name: disallow-host-namespaces
      kind: ValidatingPolicy
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace-and
      expression: "object.metadata.name.startsWith('csi-node') && object.metadata.namespace == 'kube-system'"
{{- end }}
---



{{- if eq .Values.cloudProvider "scw" }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: scaleway-konnectivity-agent
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-namespaces
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('konnectivity-agent') && object.metadata.namespace == 'kube-system'"
{{- end }}
---



{{- if eq .Values.kubernetesDistribution "k3s" }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: k3s-svclb
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-capabilities
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace-and-component
      expression: "object.metadata.name.startsWith('svclb') && object.metadata.namespace == 'kube-system'"
{{- end }}
---

{{- if eq .Values.kubernetesDistribution "k3s" }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: k3s-svclb-nginx
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-ports
      kind: ValidatingPolicy
    - name: restrict-sysctls
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace-and-component
      expression: "object.metadata.name.startsWith('svclb-nginx-ingress-ingress-nginx-controller') && object.metadata.namespace == 'kube-system'"
{{- end }}
---



{{- if include "common.used" .Values.components.security.trivy }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: trivy-node-collector
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-namespaces
      kind: ValidatingPolicy
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('node-collector') && object.metadata.namespace == '{{ .Values.components.security.trivy.namespace }}'"
{{- end }}
---

{{- if include "common.used" .Values.components.monitoring.kubePrometheusStack }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: prometheus-node-exporter
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-namespaces
      kind: ValidatingPolicy
    - name: disallow-host-path
      kind: ValidatingPolicy
    - name: disallow-host-ports
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('prometheus-prometheus-node-exporter') && object.metadata.namespace == '{{ .Values.components.monitoring.kubePrometheusStack.namespace }}'"
{{- end }}
---


{{- if include "common.used" .Values.components.monitoring.smartctlExporter }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: prometheus-smartctl-exporter
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-privileged-containers
      kind: ValidatingPolicy
    - name: disallow-host-namespaces
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-namespace
      expression: "object.metadata.namespace == '{{ .Values.components.monitoring.smartctlExporter.namespace }}'"
{{- end }}
---



{{- if include "common.used" .Values.components.security.falco }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: falco
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-privileged-containers
      kind: ValidatingPolicy
    - name: disallow-host-namespaces
      kind: ValidatingPolicy
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('falco') && object.metadata.namespace == '{{ .Values.components.security.falco.namespace }}'"
    - name: skip-by-name-and-namespace-with-prefix
      expression: "object.metadata.name.startsWith('infra-falco-falco') && object.metadata.namespace == '{{ .Values.components.security.falco.namespace }}'"
{{- end }}
---


{{- if include "common.used" .Values.components.backup.velero }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: velero-node-agent
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('node-agent') && object.metadata.namespace == '{{ .Values.components.backup.velero.namespace }}'"
{{- end }}
---

{{- if include "common.used" .Values.components.monitoring.promtail }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: promtail
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('promtail') && object.metadata.namespace == '{{ .Values.components.monitoring.promtail.namespace }}'"
{{- end }}
---


{{- if include "common.used" .Values.components.monitoring.x509CertificateExporter }}
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: x509-certificate-exporter-nodes
  namespace: infra-kyverno
  annotations:
    helm.sh/resource-policy: keep
spec:
  policyRefs:
    - name: disallow-host-path
      kind: ValidatingPolicy
  matchConditions:
    - name: skip-by-name-and-namespace
      expression: "object.metadata.name.startsWith('x509-x509-certificate-exporter') && object.metadata.namespace == '{{ .Values.components.monitoring.x509CertificateExporter.namespace }}'"
{{- end }}
---



{{- end }}
