{{/* Validate general.clusterName */}}

{{- if not .Values.general.clusterName }}
{{ fail "missing general.clusterName" }}
{{- end }}

{{- if not (regexMatch "^[a-z0-9-]+$" (toString .Values.general.clusterName)) }}
{{ fail "invalid general.clusterName" }}
{{ end }}

{{- if .Values.general.ingressWildcardSuffix }}
{{ fail "general.ingressWildcardSuffix is deprecated. use general.dnsWildcardSuffixes.ingress.nginx instead" }}
{{- end }}
